PluginOnOff: true

RandomDropOnOff: true
RandomDropProbability: 50

Item1:
  ==: org.bukkit.inventory.ItemStack
  type: DIAMOND
Item2:
  ==: org.bukkit.inventory.ItemStack
  type: DIAMOND
Item3:
  ==: org.bukkit.inventory.ItemStack
  type: DIAMOND
Item4:
  ==: org.bukkit.inventory.ItemStack
  type: DIAMOND
Item5:
  ==: org.bukkit.inventory.ItemStack
  type: DIAMOND
Item6:
  ==: org.bukkit.inventory.ItemStack
  type: DIAMOND
Item7:
  ==: org.bukkit.inventory.ItemStack
  type: DIAMOND
Item8:
  ==: org.bukkit.inventory.ItemStack
  type: DIAMOND
Item9:
  ==: org.bukkit.inventory.ItemStack
  type: DIAMOND
Item10:
  ==: org.bukkit.inventory.ItemStack
  type: DIAMOND
Item11:
  ==: org.bukkit.inventory.ItemStack
  type: DIAMOND
Item12:
  ==: org.bukkit.inventory.ItemStack
  type: DIAMOND
Item13:
  ==: org.bukkit.inventory.ItemStack
  type: DIAMOND
Item14:
  ==: org.bukkit.inventory.ItemStack
  type: DIAMOND
Item15:
  ==: org.bukkit.inventory.ItemStack
  type: DIAMOND
Item16:
  ==: org.bukkit.inventory.ItemStack
  type: DIAMOND
Item17:
  ==: org.bukkit.inventory.ItemStack
  type: DIAMOND
Item18:
  ==: org.bukkit.inventory.ItemStack
  type: DIAMOND

InventoryDropOnOff: true
InventoryDropProbability: 50

